### PR TITLE
Create an example for the documentation

### PR DESCRIPTION
**Pull request by Akendo**
For better usage, I wrote down my notes and added them to the `socket.rs` code. Should be a working example. Beside of this, I also hinting how to address the error: `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }',`

This should make it more easier to use this library. Thanks for put this up! 

best regards,
akendo

### CODE REVIEW

**Comment by svartalf** [comment]
I've updated current master to edition2018 and fixed CI tests.

Can you rebase your changes onto it?

**Comment by Akendo** [comment]
Sure

**Comment by Akendo** [comment]
I've updated it. However, the tests seem to fail at the moment. I'm going to create another issue for this.

**Comment by Akendo** [comment]
Okay. It's working now, guess there is a problem running test that is going to be solved the same fashion as #1. Not sure how I teach this to `cargo` on my local system

**Comment by svartalf** [comment]
@Akendo, great, thank you!

**Pull request merged**
